parameters:
  shop:
    # 'helloasso', 'mangopay' and in future 'stripes', 'mollie' or other
    serviceName: 'helloasso'
  shop_editable_config_params:
    - shop:
      - serviceName
      - mangoPay:
        - clientId
        - clientApiKey
      - helloAsso:
        - clientId
        - clientApiKey
        - organizationSlug

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Shop\Service\:
    resource: 'services/*Service.php'